### ISSUE TITLE
Generation of Species database

### ISSUE THREAD

**Issue by GDKO** [GuyAllard/SPINGO#12]
Hi @GuyAllard,

Since the RDP website is defunct can you recommend an alternative to download the database files?

Cheers,
Georgios

**Comment by kardokhk** [comment]
Hi there,

You can download a species-level database in .fasta format that's compatible with SPINGO. Simply move this file to the 'database' folder within the SPINGO directory and it should function smoothly. 

[https://drive.google.com/file/d/1XLpB7Dfd0_-Cnoa0SbdbRT4E2Xmib3X-/view?usp=drive_web](url)

**Comment by GDKO** [comment]
Thanks @LudinusDaleth
