### ISSUE TITLE
Taxonomy levels enhancement

### ISSUE THREAD

**Issue by bvalot** [GuyAllard/SPINGO#6]
I begin to use SPINGO and found good result in comparison to classical RDP strategy. 

It would be interesting to adapt SPINGO to use more complex taxonomy levels without restriction to 3. For example, the classical 6-7 levels use in other programs:
(superkingdom), phylum, class, order, family, genus, species

I can help to code this functionality  

Benoit

**Comment by MarcusClaesson** [comment]
Thanks for your comments and suggestions Benoit. However we have added the ability for spingo to use any number of levels. All that needs to be done is to add the extra levels as a new column in the taxonomy map then re-make the database. No programming required.
Marcus

**Comment by bvalot** [comment]
Thanks for the reply. I would test that rapidly!

Just a commentary about the taxonomy map files. I would be more easier that taxonomy would be range  from lower to higher levels (...,order, genus, species) instead like actually (species, genus, order, ...)
May be order in taxonomy map is not important?

Thanks

Benoit
