### ISSUE TITLE
build error from boost library and solution

### ISSUE THREAD

**Issue by Takadonet** [GuyAllard/SPINGO#7]
Getting the following error on ubuntu with all boost library installed as described in README

g++ makeindex.o fasta.o kmerizer.o database.o -o spindex -pthread -lboost_program_options -lboost_thread -lboost_serialization
/usr/bin/ld: makeindex.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line

Looks like adding the ''-lboost_system" to the source/makefile  fixed the issue.

**Comment by GuyAllard** [comment]
Hi,
Thanks for looking into this.

I encountered this error previously, and addressed it by adding the boost-fix=1 option which adds the -lboost_system flag to the linker options (see the COMPILATION ERRORS section at the end of the README for details). T

I have not made the -lboost_system option the default option at present as it breaks compatibility with earlier boost versions which are still widely used.

The ideal solution would be to detect which version of boost is installed, then adjust the linker flags automatically.

**Comment by Takadonet** [comment]
Thanks for the taking a look.

**Comment by Takadonet** [comment]
Is it possible to create a new release with this change? The v1.1 release does not have that boost-fix=1 option . I am in the process of making a bioconda recipe for your tool.

**Comment by GuyAllard** [comment]
I overlooked the release tags - I will create a 1.3 release which reflects the current master.

Thanks for spending time on the bioconda recipe. That will be really useful. We can add some information about it as an install option to the README when it is done.

**Comment by GuyAllard** [comment]
1.3 tag is created

**Comment by Takadonet** [comment]
Thank you.  Hope to get it push to bioconda this week if nothing interrupt
me.
